###########################################################
# Copyright 2020, Tryon Solutions, Inc.
# All rights reserved.  Proprietary and confidential.
#
# This file is subject to the license terms found at 
# https://www.cycleautomation.com/end-user-license-agreement/
#
# The methods and techniques described herein are considered
# confidential and/or trade secrets. 
# No part of this file may be copied, modified, propagated,
# or distributed except as authorized by the license.
############################################################ 
# Test Case: BASE-RCV-0100 Terminal Inbound Directed Putaway Directed Work.feature
# 
# Functional Area: Receiving
# Author: Tryon Solutions 
# Blue Yonder WMS Version: Consult Bundle Release Notes
# Test Case Type: Regression
# Blue Yonder Interfaces Interacted With: Terminal, MOCA
# 
# Description:
# This Test Case generates a receipt via MSQL, receives it, and then performs directed putaway and deposits to a staging area. From that action directed work is generated to move inventory to a system generated final location.
#
# Input Source: Test Case Inputs/BASE-RCV-0100.csv
# Required Inputs:
# 	trlr_num - This will be used as the trailer number when receiving by Trailer. If not, this will be the Receive Truck and Invoice Number
#	inv_num - This will be used as the Invoice Number when receiving by Trailer. If receiving by PO - this will not be used.
#	yard_loc - If receiving by Trailer, this is where your Trailer needs to be checked in. Must be a valid and open dock door.
#	invtyp - This need to be a valid Invoice Type, that is assigned in your system
#	prtnum - This needs to be a valid part number that is assigned in your system. Will use the default client_id.
#	rcvsts - Receiving status created on the Invoice Line being loaded
#	expqty - The number expected
# 	supnum - A valid supplier
#	rcv_qty - quantity to receive for terminal input
#	putaway_method - 1 is Directed and that wll be used for this test
#	asn_flg - Flag for ASN Receipts (False for this test)
#	actcod - Activity Code
#	lpn - use explicit LPN for load instead of one generated by system
#	oprcod - Operation Code
# Optional Inputs: 
#	rcv_prtnum - Populate this field to test blind receiving 
#	validate_loc - Location to be validated for Directed Putaway, when doing Directed Putaway only
#	lotnum - Lotnum to add to the receiving line when creating the invoice and to be used for receiving if the item is lot tracked
#	rec_loc - A valid Receiving Staging lane when using sorting putaway
#	dep_loc - A valid Receiving Staging lane for deposit for undirected putaway
#	ap_sts - Valid Aging profile status, if the part has an aging profile
#	qa_sts - Valid QA Status, if the part should be received in a QA Status
#	expect_discrepancies - on receiving completion should process expect discrepancies
#
# Assumptions:
# - Movement zones for RCVSTG have been setup and configured relative to Users and Vehicles
# - Directed Moves for STO Operation Code to Any Area has been configured for RCVSTG Movement Zone
# - Storage Zones are configured for Directed Putaway operations
# - Processing ends with the deposit into the location allocated by system and scrapped off the deposit screen
#
# Notes:
# None
#
############################################################
Feature: BASE-RCV-0100 Terminal Inbound Directed Putaway Directed Work

Background:
############################################################
# Description: Imports dependencies, sets up the environment.
#############################################################

Given I "setup the environment"
	Then I assign all chevron variables to unassigned dollar variables
	And I import scenarios from "Utilities/Base/Environment.feature"
	When I execute scenario "Set Up Environment"

	Given I execute scenario "Terminal Receiving Imports"

	Then I assign "BASE-RCV-0100" to variable "test_case"
	When I execute scenario "Test Data Triggers"

And I "load the dataset"
	Then I assign "Receiving" to variable "dataset_directory"
	And I execute scenario "Perform MOCA Dataset"
	And I assign $trlr_num to variable "trknum"
 
After Scenario: 
#############################################################
# Description: Logs out of the interface and cleans up the dataset
#############################################################

Given I "perform test completion activities including logging out of the interfaces"
	Then I execute scenario "Test Completion"

And I "cleanup the dataset"
	Then I assign "Receiving" to variable "cleanup_directory"
	And I execute scenario "Perform MOCA Cleanup Script"

@BASE-RCV-0100
Scenario Outline: BASE-RCV-0100 Terminal Inbound Directed Putaway Directed Work
CSV Examples: Test Case Inputs/BASE-RCV-0100.csv

Given I "execute pre-test scenario actions (including pre-validations)"
	And I execute scenario "Begin Pre-Test Activities"

Then I "login to the Terminal"
	When I execute scenario "Terminal Login"

When I "open the Receipt, process workflow, receive each receipt line individually, and deposit to location"
	Given I "open the Receipt"
		Then I execute scenario "Terminal LPN Receiving Menu"
		And I enter $trknum in terminal
	
	And I "check to see if we have a workflow and process the workflow"
		Then I execute scenario "Terminal Process Workflow"

	When I "perform Receiving (non-ASN)"
		Then I execute scenario "Terminal Non-ASN Receiving"

	And I "move to Product Putaway screen and process the Putaway"
		Then I execute scenario "Terminal Trigger Product Putaway"
		And I execute scenario "Terminal Process Product Putaway"
	
	And I "deposit the load to staging location"
		Then I execute scenario "Terminal Load Deposit"
        
	When I "process generated directed work from directed putaway and deposit to system generated location"
		Then I execute scenario "Terminal Navigate Quickly to Undirected Menu"
		And I execute scenario "Terminal Navigate to Directed Work Menu"
		And I execute scenario "Terminal Receiving Product Pickup Directed Work"
		And I unassign variable "dep_loc"
		And I execute scenario "Terminal Deposit"     
        
	And I "complete the receiving process"
		Then I execute scenario "Terminal Navigate Quickly to Undirected Menu"
		And I execute scenario "Terminal Complete Receiving"

And I "verify LPN is deposited properly"
	Then I assign $lpn to variable "lodnum"
	And I execute scenario "Validate Putaway Was Successful"
    
Then I "execute post-test scenario actions (including post-validations)"
	And I execute scenario "End Post-Test Activities"